# Generated by Django 4.1.2 on 2022-10-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_task_app', '0002_form_creation_time_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='name_of_responder',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
