# Generated by Django 4.1.2 on 2022-10-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship_task_app', '0003_responses_name_of_responder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='name_of_responder',
        ),
        migrations.AddField(
            model_name='responses',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internship_task_app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
