# Generated by Django 4.1.2 on 2022-10-28 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_task_app', '0005_responses_admin_alter_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='user',
            new_name='responder',
        ),
    ]
